# Generated by Django 4.2.19 on 2025-04-06 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_remove_projectfile_web_path_project_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="VideoProcessingResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("result", models.JSONField()),
                ("action_result", models.JSONField(blank=True, null=True)),
                (
                    "project_file",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.projectfile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TextProcessingResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("result", models.JSONField()),
                ("layout_dets", models.JSONField(blank=True, null=True)),
                ("page_info", models.JSONField(blank=True, null=True)),
                (
                    "project_file",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.projectfile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ImageProcessingResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("result", models.JSONField()),
                (
                    "predicted_label",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("detection_results", models.JSONField(blank=True, null=True)),
                (
                    "project_file",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.projectfile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AudioProcessingResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("result", models.JSONField()),
                ("transcription", models.TextField(blank=True, null=True)),
                ("mfccs", models.JSONField(blank=True, null=True)),
                ("spectral_centroids", models.JSONField(blank=True, null=True)),
                ("spectral_bandwidth", models.JSONField(blank=True, null=True)),
                ("spectral_flatness", models.JSONField(blank=True, null=True)),
                (
                    "project_file",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.projectfile",
                    ),
                ),
            ],
        ),
    ]
