# Generated by Django 4.2.19 on 2025-03-31 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_remove_projectfile_web_path_project_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="FileProcessingResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("result", models.JSONField()),
                (
                    "project_file",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.projectfile",
                    ),
                ),
            ],
        ),
    ]
